### ISSUE TITLE
No USB ports available in Devices Ports menu in Kobo

### ISSUE THREAD

**Issue by GrantHeaney** [XCSoar/XCSoar#692] opened 2021-08-19 00:11 UTC
XCSoar versions having and not having the problem
-------------------------------------------------
Which XCSoar version are you using when seeing the problem? Kobo 7.11
Which XCSoar version is the last one you know that did not show the problem? Kobo 6.8.11

Expected behavior
-----------------
Being able to connect multiple USB devices in the Devices menu with multiple USB ports available to be selected.

Actual behavior
---------------
In all versions of 7.XX there are no USB devices in the Ports list to choose from when connecting USB devices..
Have tested multiple kobo Mini and Kobo Glo HD devices with the same result.

Steps to reproduce the behavior
-------------------------------
A fresh install or upgrade to 7.11 exhibits the issue however, if I copy a previously configured default.prf from a 6.XX version to the XCSoarData folder of the 7.11 version it works perfectly.
If a change is required to the USB ports within Devices Ports menu there is is no oportuinity to select different USB ports.
As a work around I reload 6.XX onto a seperate Kobo, configure the USB ports as required and then copy that default.prf to the Kobo loaded with 7.11.

Do you have any idea what may have caused this?
-----------------------------------------------
Something was lost moving from 6.XX version 7

Do you have an idea how to solve the issue?
-------------------------------------------
Work around as described above

**Comment by MaxKellermann** [comment] 2021-08-19 16:03
Duplicate of https://github.com/XCSoar/XCSoar/issues/617

**Closed by MaxKellermann** 2021-08-19 16:03 UTC
