### ISSUE TITLE
B50 cruise / climb switch of displays now incorrect after fix

### ISSUE THREAD

**Issue by gldrpilot** [XCSoar/XCSoar#812] opened 2021-12-24 06:12 UTC
XCSoar versions having and not having the problem:
Having problem 7.21, not having problem 7.20
-------------------------------------------------

Expected behavior:
Using 'Flaps Forces Cruise", switching between cruise / climb from Borgelt B800 worked correctly in version 7.20 and earlier. 
-----------------

Actual behavior:
A recent 'fix' in version 7.21 has been introduced to invert this which has resulted in the circling page being displayed when cruising and cruising page being displayed when climbing.
---------------

Install version 7.21 (Android)
Connect to B800
Switch modes & observer resultant display.
(I've double checked using Mike's simulator program and changing between version 7.20 and 7.21. I've uses this feature for a number of years and it has been correct until version 7.21.)
-------------------------------

Do you have any idea what may have caused this?
A recent update to the software.

-----------------------------------------------

Do you have an idea how to solve the issue?
Remove the fix, or make an option to select a 0 or 1 as cruise or climb.

-------------------------------------------

**Comment by lordfolken** [comment] 2021-12-24 16:48
https://github.com/XCSoar/XCSoar/pull/774 this was the discussion and merge. @iltis42 can we verify?

**Comment by gldrpilot** [comment] 2021-12-24 21:22
I have double checked using the simulator, see attached file of results. This suggests the status is inverted to the published documentation as mentioned in #774 
v7.20 works in the correct sense when connected to either the B800 and the simulator.
[Cruise climb status to PBB50 string.pdf](https://github.com/XCSoar/XCSoar/files/7775149/Cruise.climb.status.to.PBB50.string.pdf)
.

**Comment by gldrpilot** [comment] 2021-12-24 21:23
Accidentally closed this...

**Comment by iltis42** [comment] 2021-12-24 21:37
Fully agree, öooks like the Borgelt documentation is wrong, exactly inverted. Hence the B50 or B800 gadgets are like this in the field, and we can't change, so we needed to revert in XCSoar in order to fix this:
https://github.com/XCSoar/XCSoar/pull/774
and i we agree this as solution, and keep the workaround of this bug in XCSoar, i will also change XCVario either to inverted cruise sense, so things will work with both gadgets in future.

**Comment by iltis42** [comment] 2022-01-03 19:25
Can we close the issue with the above reversion?
Mike Borgelt has answered my mail and confirmed by looking at the code, that documentation has twisted the sense.

**Comment by gldrpilot** [comment] 2022-01-03 20:15
Thank you, I'll close this.

**Comment by gldrpilot** [comment] 2022-01-27 09:37
Hi
I see a release of XCSoar 7.22, however the topic of this issue has not been corrected.

**Comment by gldrpilot** [comment] 2022-01-27 09:37
I see a release of XCSoar 7.22, however the topic of this issue has not been corrected.

**Comment by gldrpilot** [comment] 2022-02-14 00:47
Now release 7.23 is available but on testing this error is still in place. Any idea when it will be restored to correct sense?

Thanks -

**Comment by iltis42** [comment] 2022-03-30 08:02
Can confirm the bug is still there, somehow the fix wasn't merged. See also my comment here:
https://github.com/XCSoar/XCSoar/pull/813#issuecomment-1080001192
**Correct is bit 0 (zero) is CRUISE, and bit 1 is CIRCLING.**
I even see this change in the file-list of #813  https://github.com/XCSoar/XCSoar/pull/813/files
![image](https://user-images.githubusercontent.com/34288016/160781902-825403e0-dca4-4cfe-b3bf-319f5efe46ac.png)
Hence the current state is not like this:
![image](https://user-images.githubusercontent.com/34288016/160782151-4838ae36-cfd1-4861-a432-ed1074e7f400.png)

**Comment by iltis42** [comment] 2022-04-13 07:26
@lordfolken apparently the problem is, your fix:  https://github.com/XCSoar/XCSoar/compare/revert-774-cruiseFix
did not go into 7.23 so issue still persists. May it be possible to merge this in for the next build ?

**Closed** 2022-04-13 16:12 UTC
Labels: bug
