### ISSUE TITLE
Icons in task administration no more readable on KOBO

### ISSUE THREAD

**Issue by fraktal-sb** [XCSoar/XCSoar#1026] opened 2022-08-28 19:10 UTC
XCSoar versions having and not having the problem
-------------------------------------------------

OK 7.23
NOK 7.24

Expected behavior
-----------------

the icons in task administation are no more radable on KOBO (Glo HD, 300 PPI)

Actual behavior
---------------

on this screenshot of 7.24 icons are to small

![2022-08-28 20_59_42-Clipboard](https://user-images.githubusercontent.com/69430537/187090513-b6e0262c-22f2-426a-ac7a-27906b08a940.png)

on this screenshot of 7.23 icons are OK

![2022-08-28 20_59_01-Clipboard](https://user-images.githubusercontent.com/69430537/187090560-28947308-dfee-4ce6-85fc-716e5bc49150.png)

Steps to reproduce the behavior
-------------------------------

check 7.24 against 7.23

Do you have any idea what may have caused this?
-----------------------------------------------

no

Do you have an idea how to solve the issue?
-------------------------------------------

no

**Comment by MikeBravo15** [comment] 2022-08-29 06:21
The same for Status icons

**Comment by lordfolken** [comment] 2023-03-22 22:44
@fraktal-sb can you retest with latest update?

**Comment by fraktal-sb** [comment] 2023-03-23 09:59
tested with current head on KOBO GLO (not HD)
icons still too small (see comparision 6.8.17/7.29)
![Icons](https://user-images.githubusercontent.com/69430537/227168347-c6aa5b53-6085-4ec2-88af-c7635e208c65.png)

**Comment by ubx** [comment] 2023-03-23 17:28
> @ubx since you have current master running. Do the icons now look good?

Screenshot from Libra 2
![task-manager](https://user-images.githubusercontent.com/516680/227286807-8b6b3eb7-6cb8-4604-8238-04348f38b981.jpg)

For my taste, still a little too small

**Comment by MaxKellermann** [comment] 2024-02-27 12:51
I bisected this and found the first bad commit: ff406bf664842298cf1c710cd9b99dd13b9e8298
Obviously, this is a bad change, because it hard-codes the output sizes of the icons at certain pixel sizes, completely ignoring the physical sizes.
@lordfolken!

**Comment by MaxKellermann** [comment] 2024-02-27 13:56
If it didn't, I'd have to revert the whole commit, because it had "side effects". That commit was obviously bad - not because it was buggy - but because this change was weird and undocumented.

I didn't follow those icon changes, but I remember I was wary of merging ff406bf664842298cf1c710cd9b99dd13b9e8298 due to this exact undocumented change, but I told myself "let's not complain again this time", because people tell me I'm complaining too much. But every time I decide to not complain, it comes back to me. That's why I prefer to be strict. I rather not have a feature than merge bad code that haunts me forever.

**Comment by lordfolken** [comment] 2024-02-27 14:06
Your change now would have broken all the iconography, if i hadn´t  merged f2d0e21 and ff406bf.

**Comment by MaxKellermann** [comment] 2024-02-27 15:11
What point are you trying to make? I don't get it.

**Comment by lordfolken** [comment] 2024-02-27 16:52
On Android these icons have a normal physical size, even though its a high dpi (600+dpi) display. 
On the kobo the icon is rendered at 1:1 resolution.

**Comment by MaxKellermann** [comment] 2024-02-27 17:11
No they don't. You misunderstood the code. XCSoar assumes the small icon is 96 dpi and the big icon is 192 dpi, and scales the bitmap for display accordingly. If you saw correct sizes on Android with your bad change, it's by chance, but not by design.

**Comment by lordfolken** [comment] 2024-02-27 17:16
This is also apparent when using software rendering (OPENGL=n GLES=n) and launch xcsoar with -dpi=300x300

![image](https://github.com/XCSoar/XCSoar/assets/407371/bbf4da9e-d7f3-4f7a-885e-892494088816)

vs native 96dpi
![image](https://github.com/XCSoar/XCSoar/assets/407371/06be4047-abf3-47b9-ae3d-bc1fbf0ef10e)

So the icon's in general are not scaled along with the dpi.

**Comment by MaxKellermann** [comment] 2024-02-27 17:23
True. The software renderer is only used on the Kobo where the factor just happens to be 1, so this is not a problem.
But if you use software rendering on hi-dpi (where it was never "officially" supported), it becomes obvious that code is still missing after all these years:
https://github.com/XCSoar/XCSoar/blob/0f0d6a63343c7f33e086f8086de0903a616c5ac5/src/ui/canvas/custom/ResourceBitmap.cpp#L39-L48
Nobody ever bothered to implement that, nobody cared because the only target that uses the software renderer is the Kobo.

But it has nothing to do with this bug.

**Comment by lordfolken** [comment] 2024-02-28 00:43
The kobo mini might have had 167DPI.
The Clara HD has 300dpi.

So the root cause is lack of scaling in relation to DPI.

Resizing all icons across all platforms doesn't address this issue.

**Comment by MaxKellermann** [comment] 2024-02-28 09:49
LoadStretch implemented on Kobo: 3e12462aee5562a9d3a59bda5bbf14a683fa8e1b

**Comment by fraktal-sb** [comment] 2024-03-16 07:14
OK, tested on KOBO GLO (not HD)

![2024-03-16-06-45-05-screen](https://github.com/XCSoar/XCSoar/assets/69430537/370c6f21-c842-4480-ae04-7ec5f1c521ea)
![2024-03-16-06-52-23-screen](https://github.com/XCSoar/XCSoar/assets/69430537/93baf49f-c6be-451d-a67f-62192c56b4b0)

**Comment by lordfolken** [comment] 2024-03-16 08:53
Thank you for checking.

**Closed by lordfolken** 2024-03-16 08:53 UTC
Labels: bug, help-wanted
