### ISSUE TITLE
Terrain is still displayed after disabling terrain file in config settings (but topography is not).

### ISSUE THREAD

**Issue by groundhogxc** [XCSoar/XCSoar#1239] opened 2023-06-01 16:02 UTC
Observed in Version 7.33

This is in itself a minor issue (unless it is the sign of some problem with memory management)

Expected behavior
-----------------

When loading a terrain file by selecting an XCM file in settings > files, closing the dialog (so the file loads and shows on map), and then afterwards opening the dialog again and de-selecting the file (so the box is empty again), the terrain, topography and the waypoints strored in that XCM file should no longer be displayed. 

(No other files need to be / should be loaded for that test)

Actual behavior
---------------

The terrain still shows on the map. (but the waypoints etc. from the XCM file do disappear as expected)

Do you have any idea what may have caused this?
-----------------------------------------------

Probably the cached terrain data is not removed from memory when the internal settings are updated after the closing of the dialog.

**Comment by lordfolken** [comment] 2023-06-01 17:54
This is kind of a duplicate of #1115  when you update certain resources they are not reloaded unless you exit xcsoar.

**Comment by lordfolken** [comment] 2023-06-01 17:55
So in your case if you exit xcsoar the map would be blank on next start.

**Comment by MaxKellermann** [comment] 2023-06-01 18:20
No, not related because the file manager has no code to reload any files and this bug report is about a regression in the settings dialog, which does have code to reload files, but this combination ceased to work 2 years ago.

**Closed** 2023-06-01 18:20 UTC
