### ISSUE TITLE
Wrong altitude from Lx Eos variometer

### ISSUE THREAD

**Issue by jirimaier** [XCSoar/XCSoar#969] opened 2022-07-14 14:21 UTC
XCSoar versions having and not having the problem
this problem was likely always present

Expected behavior:
Lx Eos (used with LXNAV driver) is sending altitude in the NMEA sentence, this altitude is already recalculated for actual QNH pressure, xcsoar should use it "as is".

Actual behavior
XCSoar is treating the value as standard-pressure-altitude (relative to 1013 hPa), if correct QNH is set in XCSoar, the altitude shown will be wrong, because it is compensated twice (in both Lx Eos as well as XCSoar)

Steps to reproduce the behavior
(When sea level pressure is different from 1013) connect Lx Eos vario to XCSoar computer. Set correct altitude and QNH on Eos. Then set correct  QNH in XCSoar. Altitude shown in XCSoar will be wrong.

Do you have any idea what may have caused this?
XCSoar expects standard pressure altitude, while Lx Eos is providing QNH altitude.

Do you have an idea how to solve the issue?
Create a modified driver that would handle the altitude value correctly.

A decent workaround is to set XCSoar QNH pressure to 1013 regardless of real value, this results in correct altitude. It will however cause wrong values in vertical distance to airspace which is defined in flight levels (independent of QNH pressure).

**Comment by Scumi** [comment] 2022-07-14 14:25
Duplicate of #415 ?

**Comment by lordfolken** [comment] 2022-07-14 14:29
LXNavigation products are not supported at this time. 

And until lxnvaigation fix their device's firmware it just won't be.

(current firmware, now outputs the QNH offset in feet, but only until you takeoff. If you change the qnh thereafter the value won't be corrected and not show you the correct altitude.)

**Comment by jirimaier** [comment] 2022-07-14 14:52
It would be nice to at least have an option to "lock" the QNH at 1013 for the workaround to be more reliable. Because the QNH seems to be synced with the vario so when the correct one is set on vario, it will change the value in XCSoar and altitude goes wrong. After initial setup on ground, you will notice that AGL is way off, but if this happens in flight, you are unlikely to notice.

**Comment by jirimaier** [comment] 2022-07-19 18:32
I noticed that it works well with the Condor Simulator driver, which seems to be able to receive true altitude and then calculate the standard altitude given QNH set in XCSoar. As such a method already exists, it shouldn't be hard to duplicate the LXNAV  driver and make this small change.

**Comment by lordfolken** [comment] 2022-07-25 11:32
Sure then make the change, and try it.

**Comment by lordfolken** [comment] 2023-02-08 13:11
Closing this as we currently don't have support for LX EOS. That is being tracked in the issue #415

**Closed by lordfolken** 2023-02-08 13:11 UTC
