### ISSUE TITLE
USB-OTG setting on Clara HD crashes and bricks the Kobo

### ISSUE THREAD

**Issue by Boulderpilot1** [XCSoar/XCSoar#676] opened 2021-07-31 20:59 UTC
XCSoar versions having and not having the problem
-------------------------------------------------

 7.10, I don't know if other versions work 

Expected behavior 
-----------------

 Device should be able to run data from XC tracer III GPS to Kobo Clara HD using USB-OTG connection, as described on XC Tracer website

Actual behavior
---------------

As soon as you select USB-OTG, a prompt occurs "USB-OTG not supported for Clara HD, use at own risk?" Select yes and then Kobo immediately crashes and bricks. I re-imaged the SD to original image and retried from the beginning. The same problem occurred twice. Kobo remains bricked.

Steps to reproduce the behavior
-------------------------------

 After new install of XCSoar on Clara HD, select system, then enable USB-OTG, when prompted select "Yes" - this leads to a crash/brick

Do you have any idea what may have caused this?
-----------------------------------------------

No ideas

Do you have an idea how to solve the issue?
-------------------------------------------

No ideas

**Comment by MaxKellermann** [comment] 2021-08-23 11:34
This is not a bug. The message clearly states that the Kobo Clara HD is not supported, and you installed an incompatible kernel despite the warning. Of course it does not work.
To support the Kobo Clara HD, we need a volunteer to develop this, and that volunteer needs to have a Kobo Clara HD.

**Comment by sepi** [comment] 2021-09-01 11:30
@Boulderpilot1 is the device recoverable? Usually the term "bricked" means that the device is broken beyond repair and is now as good as a brick.

**Comment by GeekGoneOld** [comment] 2021-12-30 18:08
This has been fixed in 7.21.  The Enable USB-OTG button is greyed out for Clara HD.  Check commit ae4a195 on src/Kobo/SystemDialog.cpp

@MaxKellermann or @lordfolken  perhaps can close this issue?

**Closed** 2022-01-06 01:03 UTC
Labels: enhancement, device needed
