### ISSUE TITLE
Infobox not shown on Jotaphone 2 (Prev15, Android 5)

### ISSUE THREAD

**Issue by sasam** [XCSoar/XCSoar#386] opened 2020-05-02 16:11 UTC
v7.0-Android_prev15 have problem with infobox display, and flash red when changing display mods.
![XCSOAR_7 0 pre15_Jotaphone2](https://user-images.githubusercontent.com/566527/80869341-36301c00-8ca0-11ea-9962-77b8d7236f1b.png)

**Comment by lordfolken** [comment] 2020-05-03 13:25
MediaTek MT6580 Chipset
Mali-400 GPU

**Comment by lordfolken** [comment] 2020-05-03 13:32
Seems to be a driver issues with the device. The manufacturer refuses to fix. 
Here is another discussion about a imilar issue:
https://github.com/mrdoob/three.js/issues/9988

**Comment by kedder** [comment] 2020-05-03 20:28
This is a duplicate of #366. I have Yotaphone 2 myself and once bisected the issue to bff3273.

**Comment by lordfolken** [comment] 2020-05-04 23:12
I think XCSoar is currently not doing a good job of queering the GL extensions supported by the device. The api level change just forces the app to use a newer GLES version.

**Comment by MaxKellermann** [comment] 2020-05-07 17:43
To solve this, somebody needs an affected device and do a big debugging session with it. Without the device, nothing can be done.

**Comment by MaxKellermann** [comment] 2020-06-13 11:36
As I said: until somebody makes such a device available to a developer, nothing can be done. Closing this for now.

**Closed by MaxKellermann** 2020-06-13 11:36 UTC
Labels: breaking, bug, wontfix
