### ISSUE TITLE
CTR- Airspace not displayed

### ISSUE THREAD

**Issue by fraktal-sb** [XCSoar/XCSoar#719] opened 2021-09-10 17:01 UTC
XCSoar versions having and not having the problem
-------------------------------------------------

6.8.17 / 7.16

Expected behavior
-----------------

all airspaces (as configured) should be displayed

Actual behavior
---------------

missing airspace (s?)

Steps to reproduce the behavior
-------------------------------

- use data from https://www.lvzc.be/index.php/luchtruim/luchtruim-4 and 2021 in 7.16
- compare with 6.8.17
- see screenshots
- tested also with setup show all airspaces

![6 8 17](https://user-images.githubusercontent.com/69430537/132890408-95474f57-8524-414e-bc35-d79457a03db7.png)
![7 16](https://user-images.githubusercontent.com/69430537/132890414-462ab116-1d20-4b81-a975-de3b4e718924.png)

Do you have any idea what may have caused this?
-----------------------------------------------

no

Do you have an idea how to solve the issue?
-------------------------------------------

no

**Comment by MaxKellermann** [comment] 2021-09-10 17:04
XCSoar 7.16 is outdated and unsupported. Always update to the latest version before reporting a bug.
Probably a duplicate of https://github.com/XCSoar/XCSoar/issues/702

**Comment by fraktal-sb** [comment] 2021-09-10 17:15
sorry, my fault, tested with with 7.17. CTR still missing

**Comment by fraktal-sb** [comment] 2021-09-11 06:01
tested also with recent version (7.18) and test-airspace file (containing only airspace Luxembourg- CTR) and old version 6.8.17 with same result: CTR Luxembourg not displayed in recent version; airspace file attached. Test under Linux/Debian did also not display the airspace. Issue should be openend again.
[CTR_TEST.txt](https://github.com/XCSoar/XCSoar/files/7147295/CTR_TEST.txt)

**Comment by August2111** [comment] 2021-09-16 10:58
The problem has nothing to do with the CTR, every other CTR works as expected: But the Arc line ('DA') wouldn't be parsed correctly - and so this airspace 'contains' only one line - and so it is removed from the view( and/or list). 
This happens in all airspace classes, not in CTR only...
Maybe next week I could solve this problem

**Closed** 2021-09-16 18:00 UTC

**Comment by fraktal-sb** [comment] 2021-09-19 08:53
issue should be opened again.

reason:

Airspace of type "Luxembourg" (see file CTR-TEST, or  https://www.lvzc.be/index.php/luchtruim/luchtruim-4) ist not accepted. See screenshot with error message. The problem did not exists in 6.8.17. When accepting with "OK" and closing XCSoar next time XCSoar is not usable. The program goes directly back to the splash screen. Only removing the airspace file in the "Airspace" directory helps. This was testet in the UNIX as well in the KOBO version
![Bildschirmfoto zu 2021-09-19 10-33-47](https://user-images.githubusercontent.com/69430537/133921393-7d8ed5ba-b065-4774-9744-0ba546a37349.png)

**Comment by MaxKellermann** [comment] 2021-09-19 09:39
Different bug, new bug report. Don't cause confusion by mixing different issues in one bug report. that'll only waste everybody's time.
