### ISSUE TITLE
XCSoar 7.17 not work on Kobo Glo HD

### ISSUE THREAD

**Issue by Vantuilmv** [XCSoar/XCSoar#717] opened 2021-09-09 15:07 UTC
XCSoar versions having and not having the problem
-------------------------------------------------

Which XCSoar version are you using when seeing the problem? 
7.17

Which XCSoar version is the last one you know that did not show the problem?
7.16

Actual behavior
---------------

By clicking on Fly it loads the map and goes back to the Fly/Sim home screen

**Comment by MaxKellermann** [comment] 2021-09-09 15:12
Duplicate of https://github.com/XCSoar/XCSoar/issues/710

**Closed by MaxKellermann** 2021-09-09 15:12 UTC
